name: ikms
description: A new Flutter project.

publish_to: 'none'

version: 1.0.7+8

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^5.0.3
  get: ^4.6.5
  isar: ^3.0.5
  intl: ^0.17.0
  swipe: ^0.0.1
  shimmer: ^2.0.0
  iconsax: ^0.0.8
  grouped_list: ^5.1.2
  path_provider: ^2.0.14
  table_calendar: ^3.0.8
  dio_smart_retry: ^5.0.0
  isar_flutter_libs: ^3.0.5
  connectivity_plus: ^3.0.2
  flutter_easyloading: ^3.0.5
  custom_navigation_bar: ^0.8.2
  flutter_datetime_picker: ^1.5.1
  flutter_native_timezone: ^2.0.0
  flutter_yandex_mobile_ads: ^0.0.11
  flutter_local_notifications: ^13.0.0
  internet_connection_checker: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  isar_generator: ^3.0.5
  dependency_validator: ^3.2.2
  flutter_native_splash: ^2.2.19
  flutter_launcher_icons: ^0.12.0

flutter_icons:
  android: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#121212"
  adaptive_icon_foreground: "assets/icons/icon_adaptive.png"

flutter_native_splash:
  color: "#121212"
  image: "assets/icons/icon_splash.png"

flutter:
  generate: false
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/