name: ikms
description: Schedule of classes

publish_to: "none"

version: 1.2.5+26

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^5.7.0
  get: ^4.6.6
  gap: ^3.0.1
  intl: ^0.19.0
  swipe: ^0.0.1
  shimmer: ^3.0.0
  timezone: ^0.10.0
  iconsax_plus: ^1.0.0
  google_fonts: ^6.2.1
  grouped_list: ^6.0.0
  url_launcher: ^6.3.1
  bottom_picker: ^2.9.0
  path_provider: ^2.1.5
  dynamic_color: ^1.7.0
  table_calendar: ^3.1.3
  dio_smart_retry: ^7.0.1
  yandex_mobileads: ^7.7.0
  flutter_timezone: ^4.0.0
  connectivity_plus: ^6.1.1
  device_info_plus: ^11.2.0
  package_info_plus: ^8.1.2
  flutter_easyloading: ^3.0.5
  flutter_displaymode: ^0.6.0
  line_awesome_flutter: ^3.0.1
  flutter_local_notifications: ^18.0.1
  internet_connection_checker_plus: ^2.7.0
  isar:
    version: ^3.1.8
    hosted: https://pub.isar-community.dev/
  isar_flutter_libs:
    version: ^3.1.8
    hosted: https://pub.isar-community.dev/

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.14
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.4
  flutter_launcher_icons: ^0.14.2
  isar_generator:
    version: ^3.1.8
    hosted: https://pub.isar-community.dev/

flutter_launcher_icons:
  android: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#181818"
  adaptive_icon_foreground: "assets/icons/icon.png"

flutter_native_splash:
  color: "#181818"
  android_12:
    color: "#181818"
  image: "assets/icons/icon.png"

flutter:
  generate: false
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
