name: ikms
description: Schedule of classes

publish_to: "none"

version: 1.2.0+21

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^5.5.0+1
  get: ^4.6.6
  gap: ^3.0.1
  intl: ^0.19.0
  swipe: ^0.0.1
  isar:
    version: ^3.1.7
    hosted: https://pub.isar-community.dev/
  shimmer: ^3.0.0
  ficonsax: ^0.0.3
  timezone: ^0.9.4
  google_fonts: ^6.2.1
  grouped_list: ^6.0.0
  url_launcher: ^6.3.0
  bottom_picker: ^2.8.0
  path_provider: ^2.1.4
  dynamic_color: ^1.7.0
  table_calendar: ^3.1.2
  dio_smart_retry: ^6.0.0
  yandex_mobileads: ^7.1.0
  flutter_timezone: ^2.1.0
  connectivity_plus: ^6.0.5
  device_info_plus: ^10.1.2
  package_info_plus: ^8.0.2
  isar_flutter_libs:
    version: ^3.1.7
    hosted: https://pub.isar-community.dev/
  flutter_easyloading: ^3.0.5
  flutter_displaymode: ^0.6.0
  flutter_local_notifications: ^17.2.2
  internet_connection_checker: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.12
  flutter_lints: ^4.0.0
  isar_generator:
    version: ^3.1.7
    hosted: https://pub.isar-community.dev/
  dependency_validator: ^4.1.0
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#181818"
  adaptive_icon_foreground: "assets/icons/icon.png"

flutter_native_splash:
  color: "#181818"
  android_12:
    color: "#181818"
  image: "assets/icons/icon.png"

flutter:
  generate: false
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
