name: project_cdis
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  intl: ^0.17.0
  flutter_screenutil: ^5.5.3+2
  dio: ^4.0.6
  table_calendar: ^3.0.7
  isar: ^3.0.2
  isar_flutter_libs: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.2.7
  isar_generator: ^3.0.2
  build_runner: ^2.0.0

flutter_icons:
  android: true
  image_path: "assets/images/schedule.png"
  adaptive_icon_background: "#1F1F1F"
  adaptive_icon_foreground: "assets/images/schedule2.png"

flutter_native_splash:
  color: "#1F1F1F"
  image: "assets/images/schedule_splash.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/