name: ikms
description: A new Flutter project.

publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^4.0.6
  get: ^4.6.5
  isar: ^3.0.5
  intl: ^0.17.0
  swipe: ^0.0.1
  shimmer: ^2.0.0
  iconsax: ^0.0.8
  grouped_list: ^5.1.2
  path_provider: ^2.0.11
  table_calendar: ^3.0.8
  isar_flutter_libs: ^3.0.5
  connectivity_plus: ^3.0.2
  flutter_easyloading: ^3.0.5
  flutter_screenutil: ^5.6.0
  custom_navigation_bar: ^0.8.2
  internet_connection_checker: ^1.0.0+1
  
  flutter_yandex_mobile_ads: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2
  flutter_lints: ^2.0.1
  isar_generator: ^3.0.5
  dependency_validator: ^3.2.2
  flutter_native_splash: ^2.2.16
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  image_path: "assets/icons/schedule.png"
  adaptive_icon_background: "#1F1F1F"
  adaptive_icon_foreground: "assets/icons/schedule2.png"

flutter_native_splash:
  color: "#1F1F1F"
  image: "assets/icons/schedule_splash.png"

flutter:
  generate: false
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/