name: test-apk-build
on: [ push ]
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.2'
      - run: flutter pub get
      - run: flutter build apk --split-per-abi
      - uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: build/app/outputs/flutter-apk
          signingKeyBase64: ${{ secrets.KEYSTORE_BASE64 }}
          alias: ${{ secrets.KEYSTORE_PASSWORD_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEYSTORE_PASSWORD }}
      - uses: jungwinter/split@v1
        id: signed_files
        with:
          msg: ${{ steps.sign_app.signedReleaseFiles }}
          separator: ':'
      - name: Example Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Test release"
          files: |
            ${{ steps.signed_files._0 }}
            ${{ steps.signed_files._1 }}
            ${{ steps.signed_files._2 }}
      - uses: actions/upload-artifact@v3
        with:
          name: apk-build
          path: |
            ${{ steps.signed_files._0 }}
            ${{ steps.signed_files._1 }}
            ${{ steps.signed_files._2 }}
      - name: publish new release
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            
            Repository: ${{ github.repository }}
            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
          document: ${{ steps.signed_files._0 }}
